// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6OoD06lWPIugVBF7n80A5HxLaAruk6U',
    appId: '1:544319659149:web:749ac2e80e911e2e2496c4',
    messagingSenderId: '544319659149',
    projectId: 'shareimages-b9e75',
    authDomain: 'shareimages-b9e75.firebaseapp.com',
    storageBucket: 'shareimages-b9e75.appspot.com',
    measurementId: 'G-QGB7P6DP88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IXftpLjvweKlXGrGCRlvFajjsd7Rx0I',
    appId: '1:544319659149:android:f28d530d10c21ab62496c4',
    messagingSenderId: '544319659149',
    projectId: 'shareimages-b9e75',
    storageBucket: 'shareimages-b9e75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMIovGk43IRf7proLn67LRRCcTG4QPkKs',
    appId: '1:544319659149:ios:e5ad233f84acd1c32496c4',
    messagingSenderId: '544319659149',
    projectId: 'shareimages-b9e75',
    storageBucket: 'shareimages-b9e75.appspot.com',
    iosClientId: '544319659149-fqn6ntplsmqcouprr4qh5iq5gircku0b.apps.googleusercontent.com',
    iosBundleId: 'com.swiftapps.sharewallpap',
  );
}
